# -*- coding: utf-8 -*-
"""1841720004_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QdAaajDMAlv-LBEGS6zmcxHVZykrVNA3
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

## ------ import data example-3 ------ ##
#  load a dataset and set a column as an index (row column)
#  using pandas read_csv() function

# because I use google Collab, so the file I upload to google drive

df = pd.read_csv("/content/drive/MyDrive/Teknologi Data/fifa.csv", index_col = "Date", parse_dates = True)

#index_col = "Date" : column used as row label
#parse_date = True : indecating row label as Date

df.info()
print(df.head())  # if we are using VS Code, otherwise, df.head() for google Colab