# -*- coding: utf-8 -*-
"""1841720004_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DbH9o7eHpxnFGulS5ekyuRz7Y381jh5s
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

## ------ data overview example-1 ------ ##
#  import data from a csv flight delays dataset

# because I use google Collab, so the file I upload to google drive

df = pd.read_csv("/content/drive/MyDrive/Teknologi Data/flight_delays.csv", index_col = "Month")
df.info()
print(df.head())
print(df.tail())
print(df.isnull().sum())
print(df[df['US'].isnull()])