# -*- coding: utf-8 -*-
"""1841720004_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17H9O5cB91RjPYHZU82CPKYGKxnlsUM_J
"""

# This is a comment
print("Hello!") # This is also a comment as a code documentation