# -*- coding: utf-8 -*-
"""1841720004_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10MkQyt25HvGukYkWRY0njYhtp67643n6
"""

print(True or False)    # output : True
print(True or False)    # output : False
print ( 100 > 200)      # output : False

a=9
print ( a > 0)          # output : True

b = 10
print ( a> b)          # output : False