# -*- coding: utf-8 -*-
"""1841720004_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iqH2Kd-jN8p993Vfi5VpS2kESztKypL6
"""

x = None
print(type(x))    # output: noneType

print(x == None)  # output: True
print(x)          # output: None