# -*- coding: utf-8 -*-
"""1841720004_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19fcCUsRV5lgsEl2WfFgNzAXADQPDo5CD
"""

x = 100; y = 150; z = 22.56; hasil = x+2*y*z
print(hasil)