# -*- coding: utf-8 -*-
"""1841720004_15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yLlDA1X6uN-H6lUgSVYh3ZF9izVK3HxJ
"""

a = 10; b = 20
mylist = [1, 2, 3, 4, 5];

a = 2
if ( a in mylist):
  print ("Line 3 a is available in the given list")
else:
  print ("Line 3 a is not available in the given list")