# -*- coding: utf-8 -*-
"""1841720004_13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lYzw0ei537mbAUva-5QM15mlDYePbG3x
"""

s = "saMurai"
s.lower()   # 'samurai'
print(s)   # 'saMurai'
s2 = s.lower()
print(s2)   # 'samurai'

name = input('What is your name? ')

print('HI ' + name + '!')