# -*- coding: utf-8 -*-
"""1841720004_12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f5GlR-AM8y1QofLAfw2qbqbsu_1wNwNB
"""

# 'Double' in Single
print('"Double" in Single')   # hasil : "Double" in Single

# "Double" in Double
print("\"Double\" in Double") # hasil : "Double" in Double