# -*- coding: utf-8 -*-
"""1841720004_11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rUXoKCNEAAwZcGssyuom9K-ohRvyFXS5
"""

myStr = 'Hello, Surabaya'
print(len(myStr))

pegawai = 'Sabine'
print ("Nama : " , pegawai)
print("Pass" + "word")

# age 35
#myText = 'Ages is'
#print(myText + age)    # Error

age = 35
myText = 'Age is '
print(myText + str(age))

print("Python " * 3)