# -*- coding: utf-8 -*-
"""1841720004_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vZRh5RiokIgdaELjdASNGmiOUPZI3jOJ
"""

if False:
  print("False")
else:
  print("True")