# -*- coding: utf-8 -*-
"""1841720004_9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S4jLamIDKhMy4-ULk-72Co6lS9KZiJaa
"""

name = input('What is your name?')

print('Hi ' + name + '!')