# -*- coding: utf-8 -*-
"""1841720004_14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_TfpBhUeZUfZhiU1RiqVwKQYTskGfjqG
"""

print(str(3.14))    # '3.14'
print(int("2345"))  # 2345
print(int(75.99999))  # 75
print(float("5.678")) # 5.768
print(float(9))     # 9.0