# -*- coding: utf-8 -*-
"""1841720004_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ekR-K5F14ogA4BWHu6abLSozZRVbUQLe
"""

cabang = ['Jakarta', 'Bogor', 'Bandung', 'Solo', 'Malang', 'Surabaya', 'Banyuwangi', 'Denpasar', 'Makasar']
print(cabang)