# -*- coding: utf-8 -*-
"""1841720004_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sANSzlByD_RBOJhzx6OR2HP9T7rWYy8n
"""

counter = 100     # integer value assigment
jarak = 104.5     # floating point value
name = "Nina"     # the name variable stores a String value

# multiple assigment in one command line :
a = b = c = 200
name, city, salary = "Sabine", 'Surabaya', 70000

print(counter)
print(jarak)
print(name)
print(a, b, c)
print(city)