# -*- coding: utf-8 -*-
"""1841720004_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V5DrQaHTONdLzTU97UPuO_hsX6PeYFMf
"""

nama = 'Sabine'

kalimat = "This is a sentences."

Paragraf = """This is a paragraph.
Paragraphs are made up of several lines and sentences."""

print(nama)
print(kalimat)
print(Paragraf)

print(nama[0:5])
print(nama[2:])
print(kalimat[-8:-1])