# -*- coding: utf-8 -*-
"""1841720004_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JAmQy91dN6bBiNizrkVO4OVVBnP78o-T
"""

nilai1 = 10
nilai2 = 20
nilai3 = 100
total = nilai1 + nilai2 + nilai3
print(total)